#[path = "../features/agents/commands.rs"]
pub mod agent_capabilities;
#[path = "../features/app-data/commands.rs"]
pub mod app_data;
#[path = "../features/terminal/background.rs"]
pub mod background;
#[path = "../features/remote/cc_connect/mod.rs"]
pub mod cc_connect;
#[path = "../features/stats/ccusage.rs"]
pub mod ccusage;
#[path = "../features/terminal/suggestions.rs"]
pub mod command_suggestion;
#[path = "../features/app-data/repair/mod.rs"]
pub mod db_repair;
#[path = "../features/desktop-pet/commands.rs"]
pub mod desktop_pet;
#[path = "../features/system/fonts.rs"]
pub mod fonts;
#[path = "../features/files/commands.rs"]
pub mod fs;
#[path = "../features/git/mod.rs"]
pub mod git;
#[path = "../features/git/diff.rs"]
pub mod git_diff;
#[path = "../features/git/diff_display.rs"]
mod git_diff_display;
#[path = "../features/git/history.rs"]
pub mod git_history;
#[path = "../features/git/tools.rs"]
pub mod git_tools;
#[path = "../features/projects/worktree.rs"]
pub mod git_worktree;
#[path = "../features/history/mod.rs"]
pub mod history;
#[path = "../features/history/backup.rs"]
pub mod history_backup;
#[path = "../features/history/edit.rs"]
pub mod history_edit;
#[path = "../features/history/sources.rs"]
pub mod history_sources;
#[path = "../features/history/title.rs"]
pub mod history_title;
#[path = "../features/hooks/settings/mod.rs"]
pub mod hook_settings;
#[path = "../features/files/live_server_commands.rs"]
pub mod live_server;
#[path = "../features/system/logging.rs"]
pub mod logging;
#[path = "../features/stats/model_pricing.rs"]
pub mod model_pricing;
#[path = "../features/hooks/opencode.rs"]
pub mod opencode_hook;
#[path = "../features/projects/groups.rs"]
pub mod project_groups;
#[path = "../features/providers/commands.rs"]
pub mod provider;
#[path = "../features/providers/routing_commands.rs"]
pub mod routing;
#[path = "../features/terminal/shell_commands.rs"]
pub mod shell;
#[path = "../features/remote/ssh/mod.rs"]
pub mod ssh;
#[path = "../features/remote/config.rs"]
pub mod ssh_config;
#[path = "../features/remote/database.rs"]
pub mod ssh_db;
#[path = "../features/files/ssh.rs"]
pub mod ssh_files;
#[path = "../features/git/ssh.rs"]
pub mod ssh_git;
#[path = "../features/remote/integration.rs"]
pub mod ssh_integration;
#[path = "../features/terminal/subagent_transcript.rs"]
pub mod subagent_transcript;
#[path = "../features/sync/commands.rs"]
pub mod sync;
#[path = "../features/notifications/system.rs"]
pub mod system_notification;
#[path = "../features/system/resources.rs"]
pub mod system_resources;
#[path = "../features/terminal/commands.rs"]
pub mod terminal;
#[path = "../features/terminal/shell.rs"]
pub mod terminal_shell;
#[path = "../features/notifications/commands.rs"]
pub mod third_party_notification;
#[path = "../features/system/version.rs"]
pub mod version;
pub mod web_conversation;
pub mod web_device;
pub mod web_server;
