import type { CSSProperties } from "react";

export const TERMINAL_DIFF_ROOT_STYLE = {
  "--surface": "var(--terminal-theme-background, #0c0e10)",
  "--surface-container-low": "color-mix(in srgb, var(--terminal-theme-background, #0c0e10) 95%, var(--term-panel-fg, #ececec) 5%)",
  "--surface-container-lowest": "var(--terminal-theme-background, #0c0e10)",
  "--surface-container-high": "var(--term-panel-card, #121212)",
  "--surface-container-highest": "var(--term-panel-card-inner, #181818)",
  "--on-surface": "var(--term-panel-fg, var(--terminal-theme-foreground, #f8fafc))",
  "--on-surface-variant": "var(--term-panel-dim, var(--terminal-theme-muted, #94a3b8))",
  "--text-primary": "var(--term-panel-fg, var(--terminal-theme-foreground, #f8fafc))",
  "--text-secondary": "color-mix(in srgb, var(--term-panel-fg, #ececec) 82%, var(--term-panel-dim, #9ca0a6) 18%)",
  "--text-muted": "var(--term-panel-dim, var(--terminal-theme-muted, #94a3b8))",
  "--border": "var(--term-panel-border, color-mix(in srgb, var(--terminal-theme-foreground, #f8fafc) 14%, transparent))",
  "--primary": "var(--terminal-theme-accent, var(--term-panel-blue, #5b8def))",
  "--accent": "var(--terminal-theme-accent, var(--term-panel-blue, #5b8def))",
  "--success": "var(--term-panel-green, #3dd68c)",
  "--warning": "var(--term-panel-yellow, #e5c453)",
  "--danger": "var(--term-panel-red, #f25e5e)",
  "--interactive-hover-bg": "color-mix(in srgb, var(--surface-container-highest) 82%, var(--primary) 18%)",
  "--interactive-active-bg": "color-mix(in srgb, var(--surface-container-highest) 72%, var(--primary) 28%)",
  "--interactive-selected-bg": "color-mix(in srgb, var(--surface-container-highest) 62%, var(--primary) 38%)",
  "--interactive-selected-border": "color-mix(in srgb, var(--primary) 48%, var(--border) 52%)",
  "--interactive-focus-ring": "color-mix(in srgb, var(--primary) 42%, transparent)",
  backgroundColor: "var(--terminal-theme-background, #0c0e10)",
  borderColor: "var(--border)",
  color: "var(--text-primary)",
} as CSSProperties;

export const DEFAULT_DIFF_ROOT_STYLE = {
  backgroundColor: "var(--surface)",
  borderColor: "var(--border)",
} as CSSProperties;

export const TERMINAL_DIFF_TABLE_STYLE = {
  "--git-diff-bg": "color-mix(in srgb, var(--terminal-theme-background, #0c0e10) 91%, var(--terminal-theme-foreground, #f8fafc) 5%)",
  "--git-diff-gutter-bg": "color-mix(in srgb, var(--terminal-theme-background, #0c0e10) 84%, var(--terminal-theme-foreground, #f8fafc) 8%)",
  "--git-diff-border": "var(--file-editor-border, color-mix(in srgb, var(--terminal-theme-foreground, #f8fafc) 13%, transparent))",
  "--git-diff-text": "var(--terminal-theme-foreground, #f8fafc)",
  "--git-diff-muted": "var(--file-editor-muted, var(--terminal-theme-muted, #94a3b8))",
  "--git-diff-hunk-bg": "color-mix(in srgb, var(--terminal-theme-background, #0c0e10) 76%, var(--terminal-theme-accent, #60a5fa) 18%)",
  "--git-diff-hunk-text": "var(--terminal-theme-accent, #60a5fa)",
  "--git-diff-insert-bg": "color-mix(in srgb, var(--term-panel-green, #3dd68c) 15%, transparent)",
  "--git-diff-insert-gutter-bg": "color-mix(in srgb, var(--term-panel-green, #3dd68c) 22%, var(--terminal-theme-background, #0c0e10) 78%)",
  "--git-diff-insert-decoration": "color-mix(in srgb, var(--term-panel-green, #3dd68c) 34%, transparent)",
  "--git-diff-delete-bg": "color-mix(in srgb, var(--term-panel-red, #ff6b6b) 15%, transparent)",
  "--git-diff-delete-gutter-bg": "color-mix(in srgb, var(--term-panel-red, #ff6b6b) 22%, var(--terminal-theme-background, #0c0e10) 78%)",
  "--git-diff-delete-decoration": "color-mix(in srgb, var(--term-panel-red, #ff6b6b) 34%, transparent)",
  "--git-diff-selected-bg": "color-mix(in srgb, var(--terminal-theme-selection, var(--terminal-theme-accent, #60a5fa)) 22%, transparent)",
  "--git-diff-selected-border": "var(--terminal-theme-accent, var(--term-panel-blue, #5b8def))",
  "--git-token-comment": "var(--term-panel-dim, #9ca0a6)",
  "--git-token-punctuation": "color-mix(in srgb, var(--term-panel-fg, #ececec) 74%, var(--term-panel-dim, #9ca0a6) 26%)",
  "--git-token-keyword": "var(--term-panel-magenta, #c77dbb)",
  "--git-token-function": "var(--term-panel-blue, #5b8def)",
  "--git-token-property": "var(--term-panel-yellow, #e5c453)",
  "--git-token-deleted": "var(--term-panel-red, #f25e5e)",
  "--git-token-string": "var(--term-panel-green, #3dd68c)",
  "--git-token-number": "var(--term-panel-yellow, #e5c453)",
  "--git-token-operator": "var(--term-panel-cyan, #5ac8e0)",
  "--git-token-regex": "var(--term-panel-red, #f25e5e)",
  backgroundColor: "var(--surface-container-lowest)",
  borderColor: "var(--border)",
} as CSSProperties;
